# This is a basic workflow to help you get started with Actions

name: CI-alternate

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - uses: manusa/actions-setup-openshift@v1.0.3
      name: Set up oc
      with:
        oc version: 'v3.11.0'
    - name: Start cluster
      run: |
        oc cluster add service-catalog
        oc cluster add template-service-broker
        curl https://raw.githubusercontent.com/minishift/minishift/master/addons/xpaas/v3.10/xpaas-streams/openjdk18-image-stream.json --location --output openjdk18-image-stream.json
        oc login -u system:admin
        oc apply -f openjdk18-image-stream.json -n openshift
        oc get cm -n kube-dns
        oc login -u developer -p dummy
        oc run mydc --image=registry.access.redhat.com/ubi8/ubi --generator=run-pod/v1 --command=true sleep 3600
        while (echo && oc get pods | grep -v -E "(Running|Completed|STATUS)");do sleep 5; done
        oc exec mydc cat /etc/resolv.conf
        oc exec mydc curl https://redhat.com
        
